// <auto-generated />
namespace ZachsPetBoarding.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class resetDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(resetDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202504070425017_resetDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
